# Generated by Django 4.0.10 on 2024-02-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_credit_balance_and_more'),
        ('users', '0003_initial'),
    ]

    operations = [
    ]
