# Generated by Django 4.0.10 on 2024-02-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0002_alter_credit_balance_and_more_0003_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='UserProduct',
        # ),
    ]
