# Generated by Django 4.0.10 on 2024-02-22 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_released',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 17, 37, 54, 359630)),
        ),
    ]
