# Generated by Django 4.0.10 on 2024-02-22 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_date_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_released',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 20, 56, 47, 205596)),
        ),
    ]
